- script:
  - cd source
  - chmod +x run_tests.sh
  - wget https://downloads.tuxfamily.org/godotengine/3.0.6/Godot_v3.0.6-stable_linux_headless.64.zip
  - chmod +x Godot_v3.0.6-stable_linux_headless.64
  - Godot_v3.0.6-stable_linux_headless.64 -d -s --path . addons\gut\gut_cmdln.gd
