language: minimal
before_install:
  - cd source
  - wget "https://downloads.tuxfamily.org/godotengine/3.0.6/Godot_v3.0.6-stable_linux_headless.64.zip"
  - sudo apt-get install unzip
  - unzip Godot_v3.0.6-stable_linux_headless.64.zip
  - chmod +x Godot_v3.0.6-stable_linux_headless.64
script:
  - ./Godot_v3.0.6-stable_linux_headless.64 -d -s addons/gut/gut_cmdln.gd --path . 